In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display all columns
pd.set_option('display.max_columns', None)

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [2]:
df = pd.read_csv("E-commerece sales data 2024.csv")

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [3]:
df.head()

,user id,product id,Interaction type,Time stamp,Unnamed: 4
0,1.0,4c69b61db1fc16e7013b43fc926e502d,purchase,10/10/2023 8:00,NaN
1,2.0,66d49bbed043f5be260fa9f7fbff5957,view,11/10/2023 8:00,NaN
2,3.0,2c55cae269aebf53838484b0d7dd931a,like,12/10/2023 8:00,NaN
3,4.0,18018b6bc416dab347b1b7db79994afa,view,13/10/2023 8:00,NaN
4,5.0,e04b990e95bf73bbe6a3fa09785d7cd0,like,14/10/2023 8:00,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3294 entries, 0 to 3293
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user id           2999 non-null   float64
 1   product id        2999 non-null   str
 2   Interaction type  2871 non-null   str
 3   Time stamp        2999 non-null   str
 4   Unnamed: 4        0 non-null      float64
dtypes: float64(2), str(3)
memory usage: 128.8 KB

In [5]:
df.describe(include='all')

,user id,product id,Interaction type,Time stamp,Unnamed: 4
count,2999.000000,2999,2871,2999,0.0
unique,NaN,2999,3,366,NaN
top,NaN,4c69b61db1fc16e7013b43fc926e502d,like,10/10/2023 8:00,NaN
freq,NaN,1,1145,21,NaN
mean,1500.000000,NaN,NaN,NaN,NaN
std,865.881054,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN
25%,750.500000,NaN,NaN,NaN,NaN
50%,1500.000000,NaN,NaN,NaN,NaN
75%,2249.500000,NaN,NaN,NaN,NaN
max,2999.000000,NaN,NaN,NaN,NaN

In [6]:
df.isnull().sum()

user id              295
product id           295
Interaction type     423
Time stamp           295
Unnamed: 4          3294
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(294)

In [8]:
# Create a copy of the original dataset
clean_df = df.copy()

In [9]:
clean_df.drop(columns=['Unnamed: 4'], inplace=True)

In [10]:
clean_df.drop_duplicates(inplace=True)

In [11]:
clean_df.duplicated().sum()

np.int64(0)

In [12]:
clean_df.dropna(inplace=True)

In [13]:
clean_df.isnull().sum()

user id             0
product id          0
Interaction type    0
Time stamp          0
dtype: int64

In [14]:
clean_df['user id'] = clean_df['user id'].astype(int)

In [15]:
clean_df['Time stamp'] = pd.to_datetime(clean_df['Time stamp'])

ValueError: time data "13/10/2023 8:00" doesn't match format "%m/%d/%Y %H:%M". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [16]:
clean_df['Time stamp'] = pd.to_datetime(
    clean_df['Time stamp'],
    dayfirst=True
)

In [17]:
clean_df.info()

<class 'pandas.DataFrame'>
Index: 2871 entries, 0 to 2998
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user id           2871 non-null   int64
 1   product id        2871 non-null   str
 2   Interaction type  2871 non-null   str
 3   Time stamp        2871 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 112.1 KB

In [18]:
clean_df.head()

,user id,product id,Interaction type,Time stamp
0,1,4c69b61db1fc16e7013b43fc926e502d,purchase,2023-10-10 08:00:00
1,2,66d49bbed043f5be260fa9f7fbff5957,view,2023-10-11 08:00:00
2,3,2c55cae269aebf53838484b0d7dd931a,like,2023-10-12 08:00:00
3,4,18018b6bc416dab347b1b7db79994afa,view,2023-10-13 08:00:00
4,5,e04b990e95bf73bbe6a3fa09785d7cd0,like,2023-10-14 08:00:00

In [3]:
df = pd.read_csv("../data/E-commerece sales data 2024.csv")